FILES		= userland.md

LANG		= english
TITLE		= "EPITECH Kernel Programming"
SUBTITLE	= "Userland"
AUTHOR		= "Pierre Surply"
DATE		= "November 20, 2015"
LOGO		= "res/logo.png"
LOGOSCALE	= 0.04
PROMO		= 2016

DOC		= userland
TYPE		= beamer

DIR_TEMPLATE	= ../template
TEMPLATE	= template

include ../template/build.mk
