FILES		= idt.md \
		  irq.md \
		  concl.md

LANG		= english
TITLE		= "EPITECH Kernel Programming"
SUBTITLE	= "Events handling"
AUTHOR		= "Pierre Surply"
DATE		= "June 4, 2015"
LOGO		= "res/logo.png"
LOGOSCALE	= 0.04
PROMO		= 2016

DOC		= int
TYPE		= beamer

DIR_TEMPLATE	= ../template
TEMPLATE	= template

include ../template/build.mk
