FILES		= x86.md


LANG		= english
TITLE		= "EPITECH Kernel Programming"
SUBTITLE	= "Introduction to x86 architecture"
AUTHOR		= "Pierre Surply"
DATE		= "October 8, 2015"
LOGO		= "res/logo.png"
LOGOSCALE	= 0.04
PROMO		= 2016

DOC		= x86-intro
TYPE		= beamer

DIR_TEMPLATE	= ../template
TEMPLATE	= template

include ../template/build.mk
