FILES		= vm.md

LANG		= english
TITLE		= "EPITECH Kernel Programming"
SUBTITLE	= "Virtual memory"
AUTHOR		= "Pierre Surply"
DATE		= "November 19, 2015"
LOGO		= "res/logo.png"
LOGOSCALE	= 0.04
PROMO		= 2016

DOC		= vm
TYPE		= beamer

DIR_TEMPLATE	= ../template
TEMPLATE	= template

include ../template/build.mk
