FILES		= segmentation.md \
		  concl.md

LANG		= english
TITLE		= "EPITECH Kernel Programming"
SUBTITLE	= "Segmentation"
AUTHOR		= "Pierre Surply"
DATE		= "October 29, 2015"
LOGO		= "res/logo.png"
LOGOSCALE	= 0.04
PROMO		= 2016

DOC		= seg
TYPE		= beamer

DIR_TEMPLATE	= ../template
TEMPLATE	= template

include ../template/build.mk
