FILES		= boot.md

LANG		= english
TITLE		= "EPITECH Kernel Programming"
SUBTITLE	= "Kernel bootstrapping"
AUTHOR		= "Pierre Surply"
DATE		= "May 18, 2015"
LOGO		= "res/logo.png"
LOGOSCALE	= 0.04
PROMO		= 2016

DOC		= bootstrap
TYPE		= beamer

DIR_TEMPLATE	= ../template
TEMPLATE	= template

include ../template/build.mk
