FILES		= intro.md


LANG		= english
TITLE		= "EPITECH Kernel Programming"
SUBTITLE	= "Introduction"
AUTHOR		= "Remi Audebert\\\ Pierre Surply"
DATE		= "May 18, 2015"
LOGO		= "res/logo.png"
LOGOSCALE	= 0.04
PROMO		= 2016

DOC		= intro
TYPE		= beamer

DIR_TEMPLATE	= ../template
TEMPLATE	= template

include ../template/build.mk
